[tool.poetry]
name = "yt-lp"
version = "1.0.0"
description = "Youtube Playlist Length"
authors = ["AlexBlandin"]

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "^2023.7.6"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.5"
yapf = "^0.32.0"
pylint = "^3.0.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
line-length = 160

[tool.ruff.lint]
select = ["F", "E", "W", "N", "UP", "B", "SIM", "PD", "PL", "TRY", "FLY", "NPY", "PERF", "FURB", "RUF"]
ignore = ["W293", "E261", "PLR2004", "PLR0912"]

[tool.yapf]
based_on_style = "pep8"
indent_width = 2
continuation_indent_width = 2
column_limit = 160
blank_line_before_nested_class_or_def = false
blank_lines_around_top_level_definition = 1
coalesce_brackets = true
dedent_closing_brackets = true
indent_dictionary_value = true
indent_blank_lines = true
join_multiple_lines = false
space_between_ending_comma_and_closing_bracket = true
spaces_around_default_or_named_assign = true
spaces_before_comment = 1

[tool.isort]
ensure_newline_before_comments = true
include_trailing_comma = true
lines_after_imports = 1
use_parentheses = true
comment_prefix = " #"
multi_line_output = 3
force_grid_wrap = 0
reverse_sort = true
length_sort = true
line_length = 160
from_first = true
indent = "  "
